language: java
jdk: openjdk8

sudo: required

script:
- ./mvnw clean install -B

env:
  global:
  - secure: "ZNQiSiOUHmBm1a41B7YBOOdT30qt5Pg6pJf4ZmIjGwylYj5g0M0rltwSkIAS36A5crKWAZUdbvScqPs3DbF2eSqt/m/5OOKahxw77HMGrR0RpPaZk4/OJ+g4J12b3tchKuc9APqScPMLBKchjsDLmUYt/V6RJOXjG2ci4IB/efwqv1YBmQVajXjrmGXfYyCKeS0X4XenY1WbgVl2Ra1dV5RIAQoaia3jd7cZLUcP5M8IRErcNY36KBvvao7QypXSJ2PVrKh9n4MpeeNfR54yJ8VZhwwKybNUhZIjs9/1McIgbYPYIgZwqHYQ65bw5jjGP1g5qUik2EHnw4d7olbv3sJgdM2FZYeA3MLBMn5RWodkVAL2f/Dj7xvKRu2aefooAy8FHTeQdGaQrgQLtJtyjM9kITtNYhSFpaYNndv/D9ys1TyO9LYv6A9LDesp3EM1qKd/nyQr1VpNHlMo0/l+knhSvd3Q7nDCdM6UybP9QF0D07PKrhRTjXAGdhG+7TDXZ0JMG3cCvCOiWoGIM5nmDB8JUnqTXhtXNhbPYxYg2g5RhMLwaIAFedHaxZeY3BRxHbvnYt6gsO1UGYVwErPbPLGF/r+XOwzDqf1mIOh+cLXYf9VAmZz4aDwxnFQd3L7wOoU2VS54x0McVTlrmHj6Vm6hK066fmv6aHdcbcXjOps="

after_deploy:
  - echo "done deploying"
