language: java
jdk: openjdk8

sudo: required

script:
- ./mvnw clean install -B

env:
  global:
  - secure: "C1nY8e1r0kC9appeq0EsFt/08WB2AjVlJBdFNyZP0h60xcsP2zeSJ5eAnMHGYqjoB4NjYuCez4lRyy1wyADAzQClEsVI3VL2wvHLnXC0+uDj30YUAVNmqrIq1qnHgw9bqxY3T3dOYh6TZeIlqKeTN0rdpWnoULfIkhFUvOtHPSO26TFe+EEVyEFfsdn7wZRQlEguRergI1oE10XKqI/QvwKrZ5YC5b5LmJttHXxTj9y6oywHYHkNhqoT7alVeRCwc0pBKT4xBYms2gGt9s4Zxbcn3DRa7rTPGwE3jLQ024Tt7HPKC2afHLZXC0ysFAwZ53OugGcctTV0pmkl4pDgqqW8v3e3co/VAxBBmykLQjt37zeG7WsA/P99m9mR0nrnYgmcQlhxHJMIPrM4uSRta5/J3Mjzsw5WJkJ+zgMJUU31nH4jNpZIBdqO6icPqrqeI6Zm+NSE0EMgaPtCvvRVtormFBzDnq4Po/g53RLjb1OJabOgUJRExO9wcHFWgQJjmJChTK2pP10mfd9/NWiBleJhakR387QcuFz9k/bh4RQuMbYkp1OXd6mpZmz2OQrrAHpUKEaC8bAsj3YAPBygwZNzWYlKr000bnaL9uijE/V6ibZGNJ6FAUqkZJ/jH2Y8B6iKZSmarn0/S1pZRYdW1VaJ/xS+S1F1UE3C3/WV3J4="


after_deploy:
  - echo "done deploying"
